### ISSUE TITLE
Hydrus patch needs updateing.

### ISSUE THREAD

**Issue by Useless-Pony** [TheCrueltySage/vampire-overlay#10]
I don't want to create a new issue for this, but it seems "more proper". 

The patch needs updating again
I've tested with the latest arch version which seems to work (emerges and starts).

**Comment by TheCrueltySage** [comment]
Sure, updated the patch.
Though to be honest, it would probably be healthier if somebody who actually uses the program copied the ebuild to their overlay and updated it when things broke. Not like it's hard to fix though.
Also, feel free to reopen the issue or open the new one, whatever is more comfortable. Since it's pretty likely that this problem will happen again, I don't feel like it needs a new issue every time, but since we don't have much traffic here anyway, I'm not against it either.

**Comment by F18SuperHornet** [comment]
Hello, it's broken again in version 433. Can you please take a look?
Thank you!

**Comment by vaartis** [comment]
I have copied the ebuild to an overlay that I am one of the maintainers of. I use the program actively so, hopefully, I'll be able to keep it up to date. The overlay repository is https://github.com/pkulev/riru/.
