### ISSUE TITLE
Hydrus depedency error

### ISSUE THREAD

**Issue by lg188** [TheCrueltySage/vampire-overlay#2]
After building and executing `hydrus-client` this is printed out. 
```
Could not import lz4.
/usr/lib64/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py:16629: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
Traceback (most recent call last):
  File "/opt/hydrus/client.pyw", line 20, in <module>
    from include import ClientController
  File "/opt/hydrus/include/ClientController.py", line 12, in <module>
    raise Exception( wx_error )
Exception: Unfortunately, hydrus now requires the new Phoenix (4.x) version of wx.

Please check the 'running from source' page in the html help for more details.
```
In the gentoo repository, I can only find wxgtk-3 and nothing with phoenix. Is there a way to solve this?

**Comment by TheCrueltySage** [comment]
The issue is simple: hydrus requires new version of wxpython that isn't in the tree, seemingly because of lack of maintainers, as can be read in this bug: https://bugs.gentoo.org/632602
Also, my build dependencies are wrong, probably because I haven't been using hydrus recently.

> Is there a way to solve this?

There are several ways to solve this:
1) Install wxpython:4.0 either manually or through pip.
2) I (or you) make an ebuild for wxpython:4.0 and push it to the main tree, also probably accepting the maintenance burden.
3) I (or you) make an ebuild for wxpython:4.0 and push it to this overlay, me implicitly accepting the maintenance burden.
4) Deleting hydrus from the overlay entirely.
5) Bumping hydrus dependencies and ignoring the fact that it doesn't build, hoping the problem will be solved one day.

I will look into 2 when I will have free time, maybe into 3 if I'm unwilling to work with the main tree for some reason (I never pushed anything there, so I have no idea what standards they have or how hard maintaining is for them). Will only do 4 or 5 if everything else fails.
Also, doing either 1 or 2 or 3 by yourself would solve your problem too, if you don't mind it.
I probably also should update ebuild dependencies anyway, since as it stands it won't even look for a theoretical wxpython:4.0, and it asks for wxpython:3.0 which it doesn't need anymore. The lack of ebuild can be fixed through package.provided for now.

Installing it through pip is probably the easiest way to solve the problem for you in short-term, though it bypasses portage, which isn't a nice thing to do in general. You can use package.provided file in /etc/portage/profile to tell portage you do have a required wxpython version after I update the dependencies.

Leaving bug open for the time being.

**Comment by lg188** [comment]
There's movement around porting wxPython 4.0.3 at https://bugs.gentoo.org/667318.
This would solve this issue, but it's not done yet.

**Comment by TheCrueltySage** [comment]
Seems the tree added the new wxPython, and I kinda missed it.
WIll push the reworked hydrus ebuild shortly. Seems to work for me, but open an issue if you find any other problems (I didn't test it much).
